name: Lint Code

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Check branch name format
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^FB-[0-9]+-.+ ]]; then
            echo "This PR's branch does not match the 'FB-XXXX-description' format, skipping linting.";
            exit 1;
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Lint code with ESLint
        run: |
          npm run lint
